# Create two namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-user
  namespace: staging
---
# Secret in production namespace
apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: production
type: Opaque
data:
  database-url: cG9zdGdyZXM6Ly9sb2NhbGhvc3Q6NTQzMi9wcm9kZGI=  # postgres://localhost:5432/proddb
  api-key: cHJvZC1hcGkta2V5LTEyMzQ1Ng==  # prod-api-key-123456
---
# Secret in staging namespace
apiVersion: v1
kind: Secret
metadata:
  name: test-credentials
  namespace: staging
type: Opaque
data:
  username: dGVzdHVzZXI=  # testuser
  password: dGVzdHBhc3MxMjM=  # testpass123
