# Role to read secrets (namespace-scoped)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: staging
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
# RoleBinding to grant access only to staging namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-user-secret-access
  namespace: staging
subjects:
- kind: ServiceAccount
  name: demo-user
  namespace: staging
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
